# Generated by Django 3.1.7 on 2021-03-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='state',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='zipcode',
        ),
    ]
