# Generated by Django 3.1.7 on 2021-03-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210330_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgurl',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
