# Generated by Django 3.1.7 on 2021-04-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210401_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='products/'),
        ),
    ]
