# Generated by Django 3.1.7 on 2021-04-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='SOME STRING', max_length=250, upload_to='products/'),
        ),
    ]
